# Introduction to Numpy and Matplotlib
Numpy is a library for scientific computing in Pyhton. In this part of the course you will learn to:
 * create and display one- and multi-dimensional arrays
 * load real experimental data from files into arrays
 * use built-in Numpy functions to analyse the data
 * use the Matplotlib library to display the results
 * manipulate the arrays to change their shape and size
 
 So let's start! :)

The main numpy object is called an array. An array is a collection of items of the same type. For the start, you can imagine the array as a table of numbers. The catch is: an array is a multidimensional object. We will soon learn what this means.
To use numpy, we need to _import_ the module. This is done by writing the following at the top of our code:

In [2]:
import numpy as np

# Array creation
There are many ways to create an array, depending on the purpose. One of the most common ones are np.zeros() which gives an array with zeros, and np.arange(N), which gives us a 1-D array with N elements, starting from 0 to N-1.  

In [26]:
A = np.arange(20)
print(A)

Y= np.zeros(10)
print(Y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


If we need non-integers or a certain spacing between the elements, we use np.linspace() which linearly interpolates
between the start and the end element. 

In [5]:
start_element = 0
end_element = 4
tot_no_elements = 10

B = np.linspace(start_element, end_element, tot_no_elements)
print (B)

[ 0.          0.44444444  0.88888889  1.33333333  1.77777778  2.22222222
  2.66666667  3.11111111  3.55555556  4.        ]


Let's print individual elements or desired range of elements.

In [6]:
print (B[1]) # notice that the indexing starts from zero!
print (B[3:5])
print(B[:-1]) # numpy can also count backwards, -1 is the last element!

0.444444444444
[ 1.33333333  1.77777778]
[ 0.          0.44444444  0.88888889  1.33333333  1.77777778  2.22222222
  2.66666667  3.11111111  3.55555556]


Let's create some multidimensional arrays and see how to work with them.

In [11]:
C = np.arange(16).reshape(4,4)
print(C)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [15]:
D =  np.arange(15).reshape(3,5)
print(D)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


The dimensions of a numpy array are called axes. The number of dimensions (axes) is called a rank. To see the number of dimensions of the array, we use np.ndim(). To see the length of each dimension, we use np.shape().

In [17]:
print ('Number of dimensions')
print(np.ndim(C))
print(np.ndim(D))

print ('Shape of the arrays')
print(np.shape(C))
print(np.shape(D))

Number of dimensions
2
2
Shape of the arrays
(4, 4)
(3, 5)


Numpy is a very powerful tool and indexing can be confusing for a beginner. If you get lost, remember to always print
your result and check if it makes sense. Let's print some elements from our array D.

In [21]:
print(D[1, 2]) # element in the row number 1 (start counting from zero!)

7


# Loading array data from a file; saving to a file

Data can be loaded into an array using the function np.loadtxt() and written using np.savetxt().


In [4]:
neuro_data = np.loadtxt('sweep1_12.txt')
print(neuro_data)

np.savetxt('neuro_data_saved.txt', neuro_data)

[-890.625  -86.875 -878.125 ..., -853.125 -846.875  -83.75 ]


# Simple math with arrays

Mathematical operations such as +, -, * and / are carried out _element-wise_ in numpy arrays. Let's see what this means.


In [9]:
E = np.arange(16).reshape((4,4)) # creating a 4x4 array with elements from 0 to 15

print('before:')
print(E)

E = E + 2 # adding 2 to each element of the array
print('\n adding 2 to the array:')
print(E)

before:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 adding 2 to the array:
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]


For comparison: with lists (not numpy objects) this does not work!

In [10]:
e = [1, 2, 3, 4] # creating a list
e + 2 # adding 2 to the list

TypeError: can only concatenate list (not "int") to list

We can multiply matrices using the np.dot() function:

In [22]:
# create two numpy 3x3 arrays out of lists like this:
A = np.asarray([[1, 2, 3], [0, 1, 0], [2, 0, 1]])
B = np.asarray([[3, 0, 4], [0, 0, 1], [2, 2, 2]])

# multiply the matrices and save the result to C
C = np.dot(A,B)

# check the output
print('A:')
print(A)
print('\nB:')
print(B)
print('\nC:')
print(C)

A:
[[1 2 3]
 [0 1 0]
 [2 0 1]]

B:
[[3 0 4]
 [0 0 1]
 [2 2 2]]

C:
[[ 9  6 12]
 [ 0  0  1]
 [ 8  2 10]]


Let's see what happens if we use * instead of np.dot():

In [21]:
# create two numpy 3x3 arrays out of lists like this:
A = np.asarray([[1, 2, 3], [0, 1, 0], [2, 0, 1]])
B = np.asarray([[3, 0, 4], [0, 0, 1], [2, 2, 2]])

# multiply the matrices and save the result to C
M = A*B

# check the output
print('A:')
print(A)
print('\nB:')
print(B)
print('\nC:')
print(M)

A:
[[1 2 3]
 [0 1 0]
 [2 0 1]]

B:
[[3 0 4]
 [0 0 1]
 [2 2 2]]

C:
[[ 3  0 12]
 [ 0  0  0]
 [ 4  0  2]]


Using * performes multiplication _element-wise_, whereas np.dot( ) does matrix multiplication.

# Array filtering

Regularly when working with real data, we need to filter it to get features we are looking for. This is nothing but applying logic functions on the array. A function of choice here is np.where( ):

In [23]:
# which indices belong to the elements of the array that satifsy Element < 10?
np.where(C < 10)

(array([0, 0, 1, 1, 1, 2, 2]), array([0, 1, 0, 1, 2, 0, 1]))

In [24]:
# which elements belong to these indices?
C[np.where(C < 10)]

array([9, 6, 0, 0, 1, 8, 2])

In [25]:
# filter the array C so that every element bigger than 10 get set to 1
# and every element smaller than 10 gets set to 0
D = np.where(C < 10, 0, 1)
print(D)

[[0 0 1]
 [0 0 0]
 [0 0 1]]


# Confusing but useful operations with arrays